#!/bin/bash

#!/bin/bash

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "No git repo"
    exit 1
fi

remote_url=$(git config --get remote.origin.url)
if [ -z "$remote_url" ]; then
    echo "NO remote origin"
    exit 1
fi

web_url=$remote_url
if [[ $remote_url == git@* ]]; then
    web_url=${remote_url/:/\/}
    web_url=${web_url/git@/https:\/\/}
fi
web_url=${web_url%.git}

echo "Opening: $web_url"

# 4. open link based on os
if [[ "$OSTYPE" == "darwin"* ]]; then
    open "$web_url" # macOS
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Controllo extra per WSL (Windows Subsystem for Linux)
    if grep -q microsoft /proc/version 2>/dev/null; then
        explorer.exe "$web_url"
    else
        xdg-open "$web_url" # Linux standard
    fi
elif [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
    start "$web_url" # Windows Git Bash
else
    echo "OS not found, but this is the link: $web_url"
fi
