#!/bin/bash

DIR_2BRAIN="/home/esposigg/Documents/projects/2brain"

if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. \"the wonderful thing about tiggers\"."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name="$(date "+%Y-%m-%d")_${file_name}.md"

cd "$DIR_2BRAIN" || exit
touch "1_inbox/${formatted_file_name}"
nvim "1_inbox/${formatted_file_name}"
