#fontsize
font_family MesloLGS NF
font_size 14.0

# Transaparenza
background_opacity 0.70

# Zoom in
map ctrl+equal increase_font_size

# Zoom out
map ctrl+minus decrease_font_size

# Copy to the cilpboard
map ctrl+shift+c copy_to_clipboard

# Paste
map ctrl+shift+v paste_from_clipboard

#diablse audio bell
enable_audio_bell no

#A bit of padding(orizontale, verticale)
#restart with kitty @ set-colors --reload
window_padding_width 5

# set zsh as deafult shell
shell zsh

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME


