
#groot
#preload = ~/file/image/wallpaper/groot_1.jpg
#wallpaper = ,~/file/image/wallpaper/groot_1.jpg

#cani sui tetti
preload = ~/file/image/Wallpaper-Bank/wallpapers/Under_Starlit_Sky.png
wallpaper = ,~/file/image/Wallpaper-Bank/wallpapers/Under_Starlit_Sky.png

#cuore
#preload = /home/ris8z/file/image/wallpapers/wallpapers/maller/pump.jpg
#wallpaper = ,/home/ris8z/file/image/wallpapers/wallpapers/maller/pump.jpg

#zero two grigia
#preload = ~/file/image/desktop-background/zerotwo.jpg
#wallpaper = ,~/file/image/desktop-background/zerotwo.jpg

#zero two colori
#preload = ~/file/image/desktop-background/zerotwo1.png
#wallpaper = ,~/file/image/desktop-background/zerotwo1.png

#gojo occhi grandi blu
#preload = ~/file/image/desktop-background/gojo1.png
#wallpaper = ,~/file/image/desktop-background/gojo1.png

#gojo viola 
#preload = ~/file/image/desktop-background/gojo2.jpeg
#wallpaper = ,~/file/image/desktop-background/gojo2.jpeg

#gojo viola chill 
#preload = ~/file/image/desktop-background/gojo3.png
#wallpaper = ,~/file/image/desktop-background/gojo3.png

#gattino
#preload = ~/file/image/desktop-background/gattino.png
#wallpaper = ,~/file/image/desktop-background/gattino.png

#gattino stilizzato
#preload = ~/file/image/catppuccin-wallpapers/minimalistic/dark-cat.png
#wallpaper = ,~/file/image/catppuccin-wallpapers/minimalistic/dark-cat.png

#pac man
#preload = ~/file/image/catppuccin-wallpapers/misc/cat_pacman.png
#wallpaper = ,~/file/image/catppuccin-wallpapers/misc/cat_pacman.png

#asuna
#preload = ~/file/image/desktop-background/asuna.png
#wallpaper = ,~/file/image/desktop-background/asuna.png


#gojo stilizzato 
#preload = ~/file/image/desktop-background/gojo4.jpeg
#wallpaper = ,~/file/image/desktop-background/gojo4.jpeg



#viola citta' anime
#preload = ~/file/image/desktop-background/viola-city.jpg
#wallpaper = ,~/file/image/desktop-background/viola-city.jpg

#viola citta' anime
#preload = ~/file/image/desktop-background/rain-city.png
#wallpaper = ,~/file/image/desktop-background/rain-city.png


#sukuna viola
#preload = ~/file/image/desktop-background/sukuma.png
#wallpaper = ,~/file/image/desktop-background/sukuma.png

#sukuna viola
#preload = ~/file/image/desktop-background/sukuna-grigio.jpg
#wallpaper = ,~/file/image/desktop-background/sukuna-grigio.jpg

# ennesimo gojo
#preload = ~/file/image/desktop-background/gojosfondoviola.png
#wallpaper = ,~/file/image/desktop-background/gojosfondoviola.png














