
#preload = ~/file/image/wallpaper/groot_1.jpg
#wallpaper = ,~/file/image/wallpaper/groot_1.jpg


preload = ~/file/image/Wallpaper-Bank/wallpapers/Under_Starlit_Sky.png
wallpaper = ,~/file/image/Wallpaper-Bank/wallpapers/Under_Starlit_Sky.png
