# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C0C5CC
background         #25252C
cursor             #767E84

active_tab_foreground     #25252C
active_tab_background     #C0C5CC
inactive_tab_foreground   #C0C5CC
inactive_tab_background   #25252C

active_border_color   #C0C5CC
inactive_border_color #25252C
bell_border_color     #151B33

color0      #4B4B52
color1		#151B33
color2		#212A2D
color3		#222B2C
color4		#232C2F
color5		#35414F
color6		#384351
color7		#9CA4AD
color8		#6D7379
color9		#1B2444
color10		#2C383C
color11		#2D393B
color12		#2F3B3E
color13		#475769
color14		#4A5A6C
color15		#9CA4AD
