# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DAD3CF
background         #26272D
cursor             #978F8E

active_tab_foreground     #26272D
active_tab_background     #DAD3CF
inactive_tab_foreground   #DAD3CF
inactive_tab_background   #26272D

active_border_color   #DAD3CF
inactive_border_color #26272D
bell_border_color     #152B54

color0      #4C4C53
color1		#152B54
color2		#40383A
color3		#484347
color4		#4B5869
color5		#706258
color6		#706258
color7		#C2B8B2
color8		#87817C
color9		#1C3970
color10		#554B4E
color11		#605A5F
color12		#64758C
color13		#958275
color14		#958275
color15		#C2B8B2
