# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E7E7DD
background         #000105
cursor             #96B9CD

active_tab_foreground     #000105
active_tab_background     #E7E7DD
inactive_tab_foreground   #E7E7DD
inactive_tab_background   #000105

active_border_color   #E7E7DD
inactive_border_color #000105
bell_border_color     #244258

color0      #000105
color1		#244258
color2		#34688E
color3		#356C95
color4		#3B6E93
color5		#70827F
color6		#8B8C76
color7		#D4D4C6
color8		#94948A
color9		#305875
color10		#458ABE
color11		#4790C6
color12		#4E93C3
color13		#95ADAA
color14		#B9BA9D
color15		#D4D4C6
